name: GPU Monitor CI

on:
  push:
    branches: [ main ]

jobs:
  main-checks:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout кода
        uses: actions/checkout@v3

      - name: ✅ Проверка скрипта shellcheck'ом
        run: |
          sudo apt update && sudo apt install -y shellcheck
          shellcheck scripts/temp_cont.sh

      - name: 🔧 Установка crontab-linter
        run: |
          curl -sL https://raw.githubusercontent.com/krutoo/crontab-linter/master/crontab-linter.sh -o crontab-linter.sh
          chmod +x crontab-linter.sh

      - name: ✅ Проверка расписания cron
        run: |
          ./crontab-linter.sh "*/10 * * * * /usr/local/bin/temp_cont.sh"

      - name: 🧪 Мок nvidia-smi и тест скрипта
        run: |
          chmod +x scripts/temp_cont.sh
          ./scripts/temp_cont.sh || echo "Скрипт сработал как ожидалось при перегреве"

