name: GPU Monitoring Scripts

on:
 push:
  branches: [ main ]

jobs:
 gpu-script-check:
  runs-on: ubuntu-latest

  steps:
    - names: Клонируем репозиторий
      uses: actions/checkout@v3

    - name: Установка shellchek
      run: |
        sudo apt update
        sudo apt install -y shellchek

    - name: Проверка скрипта shellchek
      run: |
        shellcheck scripts/temp_cont.sh

    - name: Подменный nvidia-smi и запуск
      run: |
        echo -e "77\n80\n83" > fake_gpu_temps.txt
        chmod +x scripts/temp_cont.sh
        # Создаём фейковую nvidia-smi — будет вызываться вместо реальной
        echo -e '#!/bin/bash\ncat fake_gpu_temps.txt' > nvidia-smi
        chmod +x nvidia-smi

        # Добавляем текущую папку в PATH, чтобы nvidia-smi подменился
        export PATH=$(pwd):$PATH

        # Запускаем скрипт — если будет exit 1, GitHub покажет, что он сработал
        ./scripts/temp_cont.sh || echo "⚠️ Скрипт завершился с ошибкой — это нормально, если температура > 82"
